/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TravelAgency;

import Business.Airplane;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jhsnehashree
 */
public class CreateAirlinerTravelAgencyJPanel extends javax.swing.JPanel {
    private JPanel jPanelBody ;
    private TravelAgency travelAgencyObj;
    /**
     * Creates new form CreatePanelTravelAgency
     */

    CreateAirlinerTravelAgencyJPanel(JPanel jPanelBody, TravelAgency travelAgencyObj) {
        initComponents();
        setBounds(10, 10, 400, 300);
        setSize(3500, 3360);
         this.jPanelBody=jPanelBody;
         this.travelAgencyObj=travelAgencyObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBackCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAirlinerCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAirlinerFlightName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAirlinerSource = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAirlinerDestination = new javax.swing.JTextField();
        jTextFieldAirlinerStartTime = new javax.swing.JTextField();
        jTextFieldAirlinerEndTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAirlinerTotalSeats = new javax.swing.JTextField();
        jTextFieldAirlinerWindowPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAirlinerMiddlePrice = new javax.swing.JTextField();
        jTextFieldAirlinerAislePrice = new javax.swing.JTextField();
        jTextFieldAirlinerMiddleSeats = new javax.swing.JTextField();
        jTextFieldAirlinerAisleSeats = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldAirlinerWindowSeats = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonCreateAirlinerRecord = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jButtonBackCreate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBackCreate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonBackCreate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackCreate.setText("<<< Back");
        jButtonBackCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackCreateActionPerformed(evt);
            }
        });

        jLabel1.setText("Airliner Company Name");

        jLabel2.setText("Flight Name");

        jLabel3.setText("Source");

        jLabel4.setText("Destination");

        jLabel5.setText("End Time");

        jLabel6.setText("Start Time");

        jLabel7.setText("Total Seats Available");

        jLabel9.setText("Price");

        jLabel10.setText("Total Seats");

        jLabel15.setText("WINDOW");

        jLabel16.setText("MIDDLE");

        jLabel17.setText("AISLE");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel19.setText("Create Record for Airliner");

        jLabel8.setText("---------------------------------------");

        jLabel11.setText("---------------------------------------");

        jButtonCreateAirlinerRecord.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCreateAirlinerRecord.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonCreateAirlinerRecord.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateAirlinerRecord.setText("Create Airliner Record");
        jButtonCreateAirlinerRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAirlinerRecordActionPerformed(evt);
            }
        });

        jLabel12.setText("(dd-MM-yyyy:HH:mm:SS)");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setText("Travel Agency");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel19)
                                        .addGap(303, 303, 303)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAirlinerFlightName, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAirlinerCompanyName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(515, 515, 515)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(493, 493, 493)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldAirlinerStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAirlinerSource))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldAirlinerEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addComponent(jTextFieldAirlinerDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 225, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAirlinerTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jButtonBackCreate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jButtonCreateAirlinerRecord))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldAirlinerWindowSeats)
                                                    .addComponent(jTextFieldAirlinerMiddleSeats)
                                                    .addComponent(jTextFieldAirlinerAisleSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(11, 11, 11)
                                                        .addComponent(jLabel10)))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldAirlinerWindowPrice)
                                                    .addComponent(jTextFieldAirlinerMiddlePrice)
                                                    .addComponent(jTextFieldAirlinerAislePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(14, 14, 14)
                                                        .addComponent(jLabel9)))))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(458, 458, 458))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAirlinerCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAirlinerFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel19)))
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldAirlinerSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAirlinerDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAirlinerStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAirlinerEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldAirlinerWindowSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAirlinerMiddleSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAirlinerAisleSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldAirlinerTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldAirlinerWindowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAirlinerMiddlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAirlinerAislePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCreateAirlinerRecord)
                .addGap(7, 7, 7)
                .addComponent(jButtonBackCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackCreateActionPerformed
        // TODO add your handling code here:
        
        jPanelBody.remove(this);
        CardLayout layout=(CardLayout) jPanelBody.getLayout();
        layout.previous(jPanelBody);
    }//GEN-LAST:event_jButtonBackCreateActionPerformed

    private void jButtonCreateAirlinerRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAirlinerRecordActionPerformed
        // TODO add your handling code here:
        

     
         if(jTextFieldAirlinerCompanyName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Airline Company Name.");
        }
        else if(jTextFieldAirlinerFlightName.getText().equals(""))
        {
          JOptionPane.showMessageDialog(null, "Please enter Airliner's Flight Name.");  
        }
        else if(jTextFieldAirlinerSource.getText().equals(""))
        {
          JOptionPane.showMessageDialog(null, "Please enter Start Place.");  
        }
        else if(jTextFieldAirlinerDestination.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null, "Please enter End Place.");   
        }
        else if(jTextFieldAirlinerStartTime.getText().equals(""))
        {
          JOptionPane.showMessageDialog(null, "Please enter Start Time.");  
        }
        else if(jTextFieldAirlinerEndTime.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null, "Please enter End Time.");   
        }else if(jTextFieldAirlinerTotalSeats.getText().equals(""))
        {
          JOptionPane.showMessageDialog(null, "Please enter Total Seats in the Flight.");  
        }
        else if(jTextFieldAirlinerWindowSeats.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null, "Please enter Window Seats.");   
        }else if(jTextFieldAirlinerAisleSeats.getText().equals(""))
        {
          JOptionPane.showMessageDialog(null, "Please enter Aisle Seats.");  
        }
        else if(jTextFieldAirlinerMiddleSeats.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null, "Please enter Middle Seats.");   
        }else if(jTextFieldAirlinerAislePrice.getText().equals(""))
        {
          JOptionPane.showMessageDialog(null, "Please enter Aisle Seats Price.");  
        }
        else if(jTextFieldAirlinerWindowPrice.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null, "Please enter Window Seats  Price.");   
        }
         else if(jTextFieldAirlinerMiddlePrice.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null, "Please enter Middle Seats Price.");   
        }
        else{
          
            
            String airlineCompanyName=jTextFieldAirlinerCompanyName.getText();
            String airlineFlightName=jTextFieldAirlinerFlightName.getText();
            String sourcePlace=jTextFieldAirlinerSource.getText();
            String destinationPlace=jTextFieldAirlinerDestination.getText();

            
         String format = "dd-MM-yyyy:HH:mm:SS";
         SimpleDateFormat sdf = new SimpleDateFormat(format);
         
         String startDate= jTextFieldAirlinerStartTime.getText();
         String endDate= jTextFieldAirlinerEndTime.getText();
        
          Date flight_startDate = null; 
          Date flight_endDate = null; 
        
        try {
            flight_startDate = sdf.parse(startDate);
            flight_endDate = sdf.parse(endDate);
        } catch (ParseException ex) {
            Logger.getLogger(CreateAirlinerTravelAgencyJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
            int totalSeatsPresent=Integer.parseInt(jTextFieldAirlinerTotalSeats.getText());
            int windowSeats=Integer.parseInt(jTextFieldAirlinerWindowSeats.getText());
            int middleSeats=Integer.parseInt(jTextFieldAirlinerMiddleSeats.getText());        
            int aisleSeats=Integer.parseInt(jTextFieldAirlinerAisleSeats.getText());
            
            double windowPrice=Double.parseDouble(jTextFieldAirlinerWindowPrice.getText());
            double aislePrice= Double.parseDouble(jTextFieldAirlinerAislePrice.getText());       
            double middlePrice=Double.parseDouble(jTextFieldAirlinerMiddlePrice.getText());
                    
           
            
            Airplane airplaneObj=travelAgencyObj.addAirliner();
            airplaneObj.setAirlineCompany(airlineCompanyName);
            airplaneObj.setAirlinerName(airlineFlightName);
            airplaneObj.setSourcePlace(sourcePlace);
            airplaneObj.setDestinationPlace(destinationPlace);
            airplaneObj.setStartDate(flight_startDate);
            airplaneObj.setEndDate(flight_endDate);
            airplaneObj.setTotalSeatsAvailable(totalSeatsPresent);
            airplaneObj.setWindowTotal(windowSeats);
            airplaneObj.setAisleTotal(aisleSeats);
            airplaneObj.setMiddleTotal(middleSeats);
            airplaneObj.setWindowPrice(windowPrice);
            airplaneObj.setAislePrice(aislePrice);
            airplaneObj.setMiddlePrice(middlePrice);
            
            JOptionPane.showMessageDialog(null, "Airliners Record and corresponding details added Successfully."); 
        }
    }//GEN-LAST:event_jButtonCreateAirlinerRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCreate;
    private javax.swing.JButton jButtonCreateAirlinerRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAirlinerAislePrice;
    private javax.swing.JTextField jTextFieldAirlinerAisleSeats;
    private javax.swing.JTextField jTextFieldAirlinerCompanyName;
    private javax.swing.JTextField jTextFieldAirlinerDestination;
    private javax.swing.JTextField jTextFieldAirlinerEndTime;
    private javax.swing.JTextField jTextFieldAirlinerFlightName;
    private javax.swing.JTextField jTextFieldAirlinerMiddlePrice;
    private javax.swing.JTextField jTextFieldAirlinerMiddleSeats;
    private javax.swing.JTextField jTextFieldAirlinerSource;
    private javax.swing.JTextField jTextFieldAirlinerStartTime;
    private javax.swing.JTextField jTextFieldAirlinerTotalSeats;
    private javax.swing.JTextField jTextFieldAirlinerWindowPrice;
    private javax.swing.JTextField jTextFieldAirlinerWindowSeats;
    // End of variables declaration//GEN-END:variables
}
