/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TravelAgency;

import Business.Airplane;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jhsnehashree
 */
public class ViewTravelAgencyJPanel extends javax.swing.JPanel {
    private JPanel jPanelBody ;
    private Airplane airplanes;
    /**
     * Creates new form ViewTravelAgencyJPanel
     */

    ViewTravelAgencyJPanel(JPanel jPanelBody, Airplane airplanes) {
        initComponents();
        setBounds(10, 10, 400, 300);
        setSize(3500, 3360);
        this.jPanelBody=jPanelBody;
        this.airplanes=airplanes;
        populateAirlinerDetails();
    }
  private void populateAirlinerDetails()
    {
        jTextFieldAirlinerCompanyNameView.setText(airplanes.getAirlinerName());
        jTextFieldAirlinerFlightNameView.setText(airplanes.getAirlineCompany());
        jTextFieldAirlinerSourceView.setText(airplanes.getSourcePlace());
        jTextFieldAirlinerDestinationView.setText(airplanes.getDestinationPlace());
        jTextFieldAirlinerStartTimeView.setText(String.valueOf(airplanes.getStartDate()));
        jTextFieldAirlinerEndTimeView.setText(String.valueOf(airplanes.getEndDate()));
        jTextFieldAirlinerTotalSeatsView.setText(String.valueOf(airplanes.getTotalSeatsAvailable()));
        jTextFieldAirlinerWindowSeatsView.setText(String.valueOf(airplanes.getWindowTotal()));
        jTextFieldAirlinerWindowPriceView.setText(String.valueOf(airplanes.getWindowPrice()));
        jTextFieldAirlinerMiddleSeatsView.setText(String.valueOf(airplanes.getMiddleTotal()));
        jTextFieldAirlinerMiddlePriceView.setText(String.valueOf(airplanes.getMiddlePrice()));
        jTextFieldAirlinerAisleSeatsView.setText(String.valueOf(airplanes.getAisleTotal()));
        jTextFieldAirlinerAislePriceView.setText(String.valueOf(airplanes.getAislePrice()));
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAirlinerAislePriceView = new javax.swing.JTextField();
        jTextFieldAirlinerMiddleSeatsView = new javax.swing.JTextField();
        jTextFieldAirlinerAisleSeatsView = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButtonBackViewAgency = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldAirlinerCompanyNameView = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAirlinerFlightNameView = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAirlinerWindowSeatsView = new javax.swing.JTextField();
        jTextFieldAirlinerSourceView = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAirlinerDestinationView = new javax.swing.JTextField();
        jTextFieldAirlinerStartTimeView = new javax.swing.JTextField();
        jTextFieldAirlinerEndTimeView = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAirlinerTotalSeatsView = new javax.swing.JTextField();
        jTextFieldAirlinerWindowPriceView = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAirlinerMiddlePriceView = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setEnabled(false);

        jTextFieldAirlinerAislePriceView.setEnabled(false);

        jTextFieldAirlinerMiddleSeatsView.setEnabled(false);

        jTextFieldAirlinerAisleSeatsView.setEnabled(false);

        jLabel15.setText("WINDOW");

        jButtonBackViewAgency.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBackViewAgency.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonBackViewAgency.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackViewAgency.setText("<<< Back");
        jButtonBackViewAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackViewAgencyActionPerformed(evt);
            }
        });

        jLabel1.setText("Airliner Company Name");

        jLabel16.setText("MIDDLE");

        jTextFieldAirlinerCompanyNameView.setEnabled(false);

        jLabel17.setText("AISLE");

        jLabel2.setText("Flight Name");

        jTextFieldAirlinerFlightNameView.setEnabled(false);

        jLabel3.setText("Source");

        jTextFieldAirlinerWindowSeatsView.setEnabled(false);

        jTextFieldAirlinerSourceView.setEnabled(false);

        jLabel4.setText("Destination");

        jTextFieldAirlinerDestinationView.setEnabled(false);

        jTextFieldAirlinerStartTimeView.setEnabled(false);

        jTextFieldAirlinerEndTimeView.setEnabled(false);

        jLabel5.setText("End Time");

        jLabel6.setText("Start Time");

        jLabel7.setText("Total Seats Available");

        jTextFieldAirlinerTotalSeatsView.setEnabled(false);

        jTextFieldAirlinerWindowPriceView.setEnabled(false);

        jLabel9.setText("Price");

        jLabel10.setText("Total Seats");

        jTextFieldAirlinerMiddlePriceView.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("Travel Agency");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel19.setText("View Record for Airliner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAirlinerSourceView, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAirlinerStartTimeView))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAirlinerEndTimeView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAirlinerDestinationView)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAirlinerTotalSeatsView, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jButtonBackViewAgency))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldAirlinerWindowSeatsView)
                                            .addComponent(jTextFieldAirlinerMiddleSeatsView)
                                            .addComponent(jTextFieldAirlinerAisleSeatsView, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel10)))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldAirlinerWindowPriceView)
                                            .addComponent(jTextFieldAirlinerMiddlePriceView)
                                            .addComponent(jTextFieldAirlinerAislePriceView, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel9))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAirlinerCompanyNameView, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAirlinerFlightNameView))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(420, 420, 420))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAirlinerCompanyNameView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAirlinerFlightNameView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldAirlinerSourceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAirlinerDestinationView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAirlinerStartTimeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAirlinerEndTimeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldAirlinerWindowSeatsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAirlinerMiddleSeatsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAirlinerAisleSeatsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldAirlinerTotalSeatsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldAirlinerWindowPriceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAirlinerMiddlePriceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAirlinerAislePriceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jButtonBackViewAgency)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackViewAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackViewAgencyActionPerformed
        // TODO add your handling code here:
        jPanelBody.remove(this);
        Component[] componentArray = jPanelBody.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinersTravelAgencyJPanel manageAccountJPanel = (ManageAirlinersTravelAgencyJPanel) component;
        manageAccountJPanel.populateTable();
        CardLayout layout = (CardLayout) jPanelBody.getLayout();
        layout.previous(jPanelBody);
    }//GEN-LAST:event_jButtonBackViewAgencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackViewAgency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAirlinerAislePriceView;
    private javax.swing.JTextField jTextFieldAirlinerAisleSeatsView;
    private javax.swing.JTextField jTextFieldAirlinerCompanyNameView;
    private javax.swing.JTextField jTextFieldAirlinerDestinationView;
    private javax.swing.JTextField jTextFieldAirlinerEndTimeView;
    private javax.swing.JTextField jTextFieldAirlinerFlightNameView;
    private javax.swing.JTextField jTextFieldAirlinerMiddlePriceView;
    private javax.swing.JTextField jTextFieldAirlinerMiddleSeatsView;
    private javax.swing.JTextField jTextFieldAirlinerSourceView;
    private javax.swing.JTextField jTextFieldAirlinerStartTimeView;
    private javax.swing.JTextField jTextFieldAirlinerTotalSeatsView;
    private javax.swing.JTextField jTextFieldAirlinerWindowPriceView;
    private javax.swing.JTextField jTextFieldAirlinerWindowSeatsView;
    // End of variables declaration//GEN-END:variables
}
