/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Airliner.WorkAreaAirlinerJPanel;
import Business.Airplane;
import Business.TravelAgency;
import Customer.WorkAreaCustomerFlightsJPanel;
import TravelAgency.ManageAirlinersTravelAgencyJPanel;
import TravelAgency.WorkAreaTravelAgencyJPanel;
import java.awt.CardLayout;

/**
 *
 * @author jhsnehashree
 */
public class MainFrame extends javax.swing.JFrame {

    private TravelAgency travelAgencyObj;
    private Airplane airplane_Obj;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(String header) {
        initComponents();
        setBounds(10, 10, 400, 300);
        setSize(3500, 3360);
        this.travelAgencyObj=new TravelAgency();
    
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelHeader = new javax.swing.JPanel();
        jButtonBookFlightHeader = new javax.swing.JButton();
        jButtonManageFlightsHeader = new javax.swing.JButton();
        jButtonManageAirlinesHeader = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanelHeader.setBackground(new java.awt.Color(255, 102, 102));

        jButtonBookFlightHeader.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBookFlightHeader.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonBookFlightHeader.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookFlightHeader.setText("Customer");
        jButtonBookFlightHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookFlightHeaderActionPerformed(evt);
            }
        });

        jButtonManageFlightsHeader.setBackground(new java.awt.Color(0, 0, 0));
        jButtonManageFlightsHeader.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonManageFlightsHeader.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageFlightsHeader.setText("Airline Company");
        jButtonManageFlightsHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFlightsHeaderActionPerformed(evt);
            }
        });

        jButtonManageAirlinesHeader.setBackground(new java.awt.Color(0, 0, 0));
        jButtonManageAirlinesHeader.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonManageAirlinesHeader.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageAirlinesHeader.setText("Travel Agency");
        jButtonManageAirlinesHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageAirlinesHeaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonManageAirlinesHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonManageFlightsHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBookFlightHeader)
                .addGap(19, 19, 19))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBookFlightHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonManageFlightsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonManageAirlinesHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanelHeader);

        jPanelBody.setBackground(new java.awt.Color(255, 204, 204));
        jPanelBody.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setText("System to Manage Airlines");
        jPanelBody.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(jPanelBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManageAirlinesHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageAirlinesHeaderActionPerformed
        // TODO add your handling code here:
        WorkAreaTravelAgencyJPanel panel=new WorkAreaTravelAgencyJPanel(jPanelBody,travelAgencyObj);
        jPanelBody.add("WorkAreaTravelAgencyJPanel",panel);
        CardLayout layout=(CardLayout) jPanelBody.getLayout();
        layout.next(jPanelBody);
        
    }//GEN-LAST:event_jButtonManageAirlinesHeaderActionPerformed

    private void jButtonManageFlightsHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFlightsHeaderActionPerformed
        // TODO add your handling code here:
        WorkAreaAirlinerJPanel panel=new WorkAreaAirlinerJPanel(jPanelBody,travelAgencyObj);
        jPanelBody.add("WorkAreaAirlinerJPanel",panel);
        CardLayout layout=(CardLayout) jPanelBody.getLayout();
        layout.next(jPanelBody);
    }//GEN-LAST:event_jButtonManageFlightsHeaderActionPerformed

    private void jButtonBookFlightHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookFlightHeaderActionPerformed
        // TODO add your handling code here:
      
        WorkAreaCustomerFlightsJPanel panel=new WorkAreaCustomerFlightsJPanel(jPanelBody,travelAgencyObj);
        jPanelBody.add("WorkAreaCustomerFlightsJPanel",panel);
        CardLayout layout=(CardLayout) jPanelBody.getLayout();
        layout.next(jPanelBody);
    }//GEN-LAST:event_jButtonBookFlightHeaderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame("Manage Airline System").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookFlightHeader;
    private javax.swing.JButton jButtonManageAirlinesHeader;
    private javax.swing.JButton jButtonManageFlightsHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
