/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Airliner.ManageAirlinerJPanel;
import Business.Airplane;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jhsnehashree
 */
public class BookFlightJPanel extends javax.swing.JPanel {
 private JPanel jPanelBody ;
 private TravelAgency travelAgencyObj;
 private Airplane airplanesObj;

 
    /**
     * Creates new form BookFlightJPanel
     */
   
        BookFlightJPanel(JPanel jPanelBody, Airplane airplanesObj,TravelAgency travelAgencyObj) {
        initComponents();
        setBounds(10, 10, 400, 300);
        setSize(3500, 3360);
         this.jPanelBody=jPanelBody;
         this.airplanesObj=airplanesObj;
         this.travelAgencyObj=travelAgencyObj;
  
         populateDetailsToBookFlight();
         blockBookedSeats(airplanesObj);
              jTextFieldCustomerPhoneNumber.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
         
    
    }
     private void blockBookedSeats(Airplane airplanesObj)
    {
        
        String blockedSeatCustomer= airplanesObj.getCustomerSeatNo();
        
        if(blockedSeatCustomer!=null)
        {
        if(blockedSeatCustomer.contains("Window-Seat Num-1"))
           {
             jButtonSeatW1.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Window-Seat Num-2"))
           {
             jButtonSeatW2.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Window-Seat Num-3"))
           {
             jButtonSeatW3.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Window-Seat Num-4"))
           {
             jButtonSeatW4.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Middle-Seat Num-5"))
           {
             jButtonSeatMid5.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Middle-Seat Num-6"))
           {
             jButtonSeatMid6.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Middle-Seat Num-7"))
           {
             jButtonSeatMid7.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Middle-Seat Num-8"))
           {
             jButtonSeatMid8.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Aisle-Seat Num-9"))
           {
             jButtonSeatAi9.setEnabled(false);  
           }
         if(blockedSeatCustomer.contains("Aisle-Seat Num-10"))
           {
             jButtonSeatAis10.setEnabled(false);  
           }
         if (blockedSeatCustomer.contains("Aisle-Seat Num-11"))
           {
             jButtonSeatAis11.setEnabled(false);  
           }
       
        }
        

    }
        private void populateDetailsToBookFlight()
    {
        jLabelAirlineNameGet.setText(airplanesObj.getAirlineCompany());
        jLabelFlightNumberGet.setText(airplanesObj.getAirlinerName());
        jLabelToGet.setText(airplanesObj.getDestinationPlace());
        jLabelFromGet.setText(airplanesObj.getSourcePlace());
        jLabelStartGet.setText(String.valueOf(airplanesObj.getStartDate()));
        jLabelEndGet.setText(String.valueOf(airplanesObj.getEndDate())); 
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelAirlineNameGet = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelFlightNumberGet = new javax.swing.JLabel();
        jLabelFromGet = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelToGet = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jTextFieldCustomerPhoneNumber = new javax.swing.JTextField();
        jButtonSeatW1 = new javax.swing.JButton();
        jButtonSeatMid5 = new javax.swing.JButton();
        jButtonSeatAi9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelStartGet = new javax.swing.JLabel();
        jLabelFinishJ = new javax.swing.JLabel();
        jLabelEndGet = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonSeatW2 = new javax.swing.JButton();
        jButtonSeatMid6 = new javax.swing.JButton();
        jButtonSeatAis10 = new javax.swing.JButton();
        jButtonSeatW3 = new javax.swing.JButton();
        jButtonSeatMid7 = new javax.swing.JButton();
        jButtonSeatAis11 = new javax.swing.JButton();
        jButtonSeatW4 = new javax.swing.JButton();
        jButtonSeatMid8 = new javax.swing.JButton();
        jButtonSeatAis12 = new javax.swing.JButton();
        jButtonBackBookFlight = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Airline Name : ");

        jLabelAirlineNameGet.setText("-");

        jLabel3.setText("Flight Number : ");

        jLabelFlightNumberGet.setText("-");

        jLabelFromGet.setText("-");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("to");

        jLabelToGet.setText("-");

        jLabel8.setText("Customer Name");

        jLabel9.setText("Customer Phone Number");

        jButtonSeatW1.setText("1");
        jButtonSeatW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatW1ActionPerformed(evt);
            }
        });

        jButtonSeatMid5.setText("5");
        jButtonSeatMid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatMid5ActionPerformed(evt);
            }
        });

        jButtonSeatAi9.setText("9");
        jButtonSeatAi9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatAi9ActionPerformed(evt);
            }
        });

        jLabel2.setText("Start Journey");

        jLabelStartGet.setText("-");

        jLabelFinishJ.setText("Finish Journey");

        jLabelEndGet.setText("-");

        jLabel4.setText("Timings :::::");

        jLabel5.setText("Window");

        jLabel10.setText("Middle");

        jLabel11.setText("Aisle");

        jButtonSeatW2.setText("2");
        jButtonSeatW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatW2ActionPerformed(evt);
            }
        });

        jButtonSeatMid6.setText("6");
        jButtonSeatMid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatMid6ActionPerformed(evt);
            }
        });

        jButtonSeatAis10.setText("10");
        jButtonSeatAis10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatAis10ActionPerformed(evt);
            }
        });

        jButtonSeatW3.setText("3");
        jButtonSeatW3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatW3ActionPerformed(evt);
            }
        });

        jButtonSeatMid7.setText("7");
        jButtonSeatMid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatMid7ActionPerformed(evt);
            }
        });

        jButtonSeatAis11.setText("11");
        jButtonSeatAis11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatAis11ActionPerformed(evt);
            }
        });

        jButtonSeatW4.setText("4");
        jButtonSeatW4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatW4ActionPerformed(evt);
            }
        });

        jButtonSeatMid8.setText("8");
        jButtonSeatMid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatMid8ActionPerformed(evt);
            }
        });

        jButtonSeatAis12.setText("12");
        jButtonSeatAis12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatAis12ActionPerformed(evt);
            }
        });

        jButtonBackBookFlight.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBackBookFlight.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackBookFlight.setText("<< Back");
        jButtonBackBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackBookFlightActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Customer");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel12.setText("Click on Seat Number for Reservation >>>>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelAirlineNameGet))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelFromGet)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelFlightNumberGet)))
                                .addGap(16, 16, 16)
                                .addComponent(jLabelToGet))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonBackBookFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabelFinishJ))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEndGet)
                                    .addComponent(jLabelStartGet)))
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCustomerPhoneNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonSeatW1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSeatW2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSeatW3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel5)))
                            .addComponent(jButtonSeatW4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSeatMid7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonSeatMid6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonSeatMid5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonSeatMid8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSeatAis11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSeatAis10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addComponent(jButtonSeatAi9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel11))
                            .addComponent(jButtonSeatAis12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelAirlineNameGet))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelFlightNumberGet))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFromGet)
                            .addComponent(jLabel6)
                            .addComponent(jLabelToGet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelStartGet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFinishJ)
                            .addComponent(jLabelEndGet))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeatAis11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeatMid7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeatMid8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeatAis12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeatW1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeatMid5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeatAi9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeatW2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeatMid6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeatAis10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBackBookFlight)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonSeatW3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(3, 3, 3)
                                .addComponent(jButtonSeatW4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)))
                        .addGap(17, 17, 17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeatW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatW1ActionPerformed
        // TODO add your handling code here:
        String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
        String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
        
        if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 1 - Window ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;
            int windowTotal= airplanes_lst.getWindowTotal()-1;
            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;
            String customerNames;
            String customerPhNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
             customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
             customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " + customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Window-Seat Num-1";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Window-Seat Num-1";
            }
            airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);
            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);
            
            airplanes_lst.setWindowTotal(windowTotal);
            
            airplanes_lst.setCustomerName(customerNames);
            airplanes_lst.setCustomerSeatNo(customerseatNos);
            airplanes_lst.setCustomerPhoneNo(customerPhNos);
            
            jButtonSeatW1.setEnabled(false);
            jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
        
    }//GEN-LAST:event_jButtonSeatW1ActionPerformed

    private void jButtonSeatW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatW2ActionPerformed
        // TODO add your handling code here:
        String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
        String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 2 - Window ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

            int windowTotal= airplanes_lst.getWindowTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
              customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Window-Seat Num-2";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Window-Seat Num-2";
            }

            airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

            airplanes_lst.setWindowTotal(windowTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

              airplanes_lst.setCustomerPhoneNo(customerPhNos);
                  jButtonSeatW2.setEnabled(false);
                    jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatW2ActionPerformed

    private void jButtonSeatW3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatW3ActionPerformed
        // TODO add your handling code here:
        String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 3 - Window ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
           int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

            int windowTotal= airplanes_lst.getWindowTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;


            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                 customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
              customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Window-Seat Num-3";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Window-Seat Num-3";
            }

            airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

            airplanes_lst.setWindowTotal(windowTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

              airplanes_lst.setCustomerPhoneNo(customerPhNos);
                jButtonSeatW3.setEnabled(false);
                  jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatW3ActionPerformed

    private void jButtonSeatW4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatW4ActionPerformed
        // TODO add your handling code here:
        String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 4 - Window ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

            int windowTotal= airplanes_lst.getWindowTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;


            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
              customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
                customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;


            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Window-Seat Num-4";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Window-Seat Num-4";
            }

           airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

            airplanes_lst.setWindowTotal(windowTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

           airplanes_lst.setCustomerPhoneNo(customerPhNos);
              jButtonSeatW4.setEnabled(false);
                jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatW4ActionPerformed

    private void jButtonSeatMid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatMid5ActionPerformed
        // TODO add your handling code here:
        String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
         String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 5 - Middle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

            int midTotal= airplanes_lst.getMiddleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
             customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Middle-Seat Num-5";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Middle-Seat Num-5";
            }

             airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

            airplanes_lst.setMiddleTotal(midTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

           airplanes_lst.setCustomerPhoneNo(customerPhNos);
            jButtonSeatMid5.setEnabled(false);
              jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatMid5ActionPerformed

    private void jButtonSeatMid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatMid6ActionPerformed
        // TODO add your handling code here:
         String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
        if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 6 - Middle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         { 
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            
int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

           int midTotal= airplanes_lst.getMiddleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;


            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                 customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
              customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Middle-Seat Num-6";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Middle-Seat Num-6";
            }

          airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

     airplanes_lst.setMiddleTotal(midTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

           airplanes_lst.setCustomerPhoneNo(customerPhNos);


              jButtonSeatMid6.setEnabled(false);
                jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatMid6ActionPerformed

    private void jButtonSeatMid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatMid7ActionPerformed
        // TODO add your handling code here:
         String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
        String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 7 - Middle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

           int midTotal= airplanes_lst.getMiddleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                 customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
               customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Middle-Seat Num-7";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Middle-Seat Num-7";
            }

             airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

     airplanes_lst.setMiddleTotal(midTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

            airplanes_lst.setCustomerPhoneNo(customerPhNos);
               jButtonSeatMid7.setEnabled(false);
                 jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatMid7ActionPerformed

    private void jButtonSeatMid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatMid8ActionPerformed
        // TODO add your handling code here:
         String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 8 - Middle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

           int midTotal= airplanes_lst.getMiddleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
               customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
               customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Middle-Seat Num-8";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Middle-Seat Num-8";
            }

          airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

     airplanes_lst.setMiddleTotal(midTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

             airplanes_lst.setCustomerPhoneNo(customerPhNos);
               jButtonSeatMid8.setEnabled(false);
                 jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatMid8ActionPerformed

    private void jButtonSeatAi9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatAi9ActionPerformed
        // TODO add your handling code here:
         String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
        if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 9 - Aisle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         { 
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

           int aisleTotal= airplanes_lst.getAisleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;


            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
             customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
                customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Aisle-Seat Num-9";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Aisle-Seat Num-9";
            }

           airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

     airplanes_lst.setAisleTotal(aisleTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

             airplanes_lst.setCustomerPhoneNo(customerPhNos);
              jButtonSeatAi9.setEnabled(false);
                jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatAi9ActionPerformed

    private void jButtonSeatAis10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatAis10ActionPerformed
        // TODO add your handling code here:
         String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 10 - Aisle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

        int aisleTotal= airplanes_lst.getAisleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;


            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                 customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
                customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Aisle-Seat Num-10";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Aisle-Seat Num-10";
            }

           airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

airplanes_lst.setAisleTotal(aisleTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

           airplanes_lst.setCustomerPhoneNo(customerPhNos);
             jButtonSeatAis10.setEnabled(false);
               jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatAis10ActionPerformed

    private void jButtonSeatAis11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatAis11ActionPerformed
        // TODO add your handling code here:
         String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 11 - Aisle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
          int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

        int aisleTotal= airplanes_lst.getAisleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;


            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                 customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
                customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Aisle-Seat Num-11";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Aisle-Seat Num-11";
            }

            airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

airplanes_lst.setAisleTotal(aisleTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

            airplanes_lst.setCustomerPhoneNo(customerPhNos);


               jButtonSeatAis11.setEnabled(false);
                 jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatAis11ActionPerformed

    private void jButtonSeatAis12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatAis12ActionPerformed
        // TODO add your handling code here:
         String flightNumber= jLabelFlightNumberGet.getText();
        String customerName=jTextFieldCustomerName.getText();
          String customerPhoneNo=jTextFieldCustomerPhoneNumber.getText();
         if(jTextFieldCustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer Name.");
        }
        else
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Click Yes to Book Confirm Seat Number 12 - Aisle ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
       for (Airplane airplanes_lst : travelAgencyObj.getAirplaneCompany()) {
            if(airplanes_lst.getAirlinerName().equalsIgnoreCase(flightNumber))
            {
            int totalSeatsBooked= airplanes_lst.getTotalSeatsBooked()+1;

        int aisleTotal= airplanes_lst.getAisleTotal()-1;

            int totalSeatsAvailable=airplanes_lst.getTotalSeatsAvailable()-1;

            String customerNames;

            String customerPhNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerNames=customerName;
                customerPhNos=customerPhoneNo;
            }
            else
            {
             customerNames=airplanes_lst.getCustomerName()+ " , " + customerName ;
               customerPhNos=airplanes_lst.getCustomerPhoneNo()+ " , " +customerPhoneNo;
            }
            String customerseatNos;
            if(airplanes_lst.getCustomerName() == null)
            {
             customerseatNos="Aisle-Seat Num-12";
            }
            else
            {
             customerseatNos=airplanes_lst.getCustomerSeatNo()+" , " + "Aisle-Seat Num-12";
            }

          airplanes_lst.setTotalSeatsAvailable(totalSeatsAvailable);

            airplanes_lst.setTotalSeatsBooked(totalSeatsBooked);

            

airplanes_lst.setAisleTotal(aisleTotal);

            

            airplanes_lst.setCustomerName(customerNames);

            airplanes_lst.setCustomerSeatNo(customerseatNos);

           airplanes_lst.setCustomerPhoneNo(customerPhNos);
                jButtonSeatAis12.setEnabled(false);
                  jTextFieldCustomerPhoneNumber.setText("");
            jTextFieldCustomerName.setText("");
        }
       }
         }
       }
    }//GEN-LAST:event_jButtonSeatAis12ActionPerformed

    private void jButtonBackBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackBookFlightActionPerformed
        // TODO add your handling code here:
        jPanelBody.remove(this);
        Component[] componentArray = jPanelBody.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BestFlightsJPanel bestFlightsJPanel = (BestFlightsJPanel) component;
        bestFlightsJPanel.populateTable();
        CardLayout layout = (CardLayout) jPanelBody.getLayout();
        layout.previous(jPanelBody);
    }//GEN-LAST:event_jButtonBackBookFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackBookFlight;
    private javax.swing.JButton jButtonSeatAi9;
    private javax.swing.JButton jButtonSeatAis10;
    private javax.swing.JButton jButtonSeatAis11;
    private javax.swing.JButton jButtonSeatAis12;
    private javax.swing.JButton jButtonSeatMid5;
    private javax.swing.JButton jButtonSeatMid6;
    private javax.swing.JButton jButtonSeatMid7;
    private javax.swing.JButton jButtonSeatMid8;
    private javax.swing.JButton jButtonSeatW1;
    private javax.swing.JButton jButtonSeatW2;
    private javax.swing.JButton jButtonSeatW3;
    private javax.swing.JButton jButtonSeatW4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAirlineNameGet;
    private javax.swing.JLabel jLabelEndGet;
    private javax.swing.JLabel jLabelFinishJ;
    private javax.swing.JLabel jLabelFlightNumberGet;
    private javax.swing.JLabel jLabelFromGet;
    private javax.swing.JLabel jLabelStartGet;
    private javax.swing.JLabel jLabelToGet;
    private javax.swing.JTextField jTextFieldCustomerName;
    private javax.swing.JTextField jTextFieldCustomerPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
