/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Airliner.CreateAirlinerJPanel;
import Business.Airplane;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author jhsnehashree
 */
public class WorkAreaCustomerFlightsJPanel extends javax.swing.JPanel {
    private JPanel jPanelBody ;
    private TravelAgency travelAgencyObj;
    private Airplane airplane_Obj;
    /**
     * Creates new form WorkAreaCustomerFlightsJPanel
     */
    

    public WorkAreaCustomerFlightsJPanel(JPanel jPanelBody, TravelAgency travelAgencyObj) {
      initComponents();
      setBounds(10, 10, 400, 300);
      setSize(3500, 3360);
      this.jPanelBody=jPanelBody;
      this.travelAgencyObj=travelAgencyObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSearchForBestFlight = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelTitleAgency = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jButtonSearchForBestFlight.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSearchForBestFlight.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchForBestFlight.setText("Search for Best Flights");
        jButtonSearchForBestFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchForBestFlightActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Customer");

        jLabelTitleAgency.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabelTitleAgency.setText("Welcome Customer ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSearchForBestFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTitleAgency)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchForBestFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelTitleAgency)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchForBestFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchForBestFlightActionPerformed
        // TODO add your handling code here:
        
         BestFlightsJPanel panel=new BestFlightsJPanel(jPanelBody,travelAgencyObj);
        jPanelBody.add("BestFlightsJPanel",panel);
        CardLayout layout=(CardLayout) jPanelBody.getLayout();
        layout.next(jPanelBody);
    }//GEN-LAST:event_jButtonSearchForBestFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchForBestFlight;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitleAgency;
    // End of variables declaration//GEN-END:variables
}
