/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Airliner;

import Business.Airplane;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jhsnehashree
 */
public class CreateAirlinerJPanel extends javax.swing.JPanel {
 private JPanel jPanelBody ;
 private TravelAgency travelAgencyObj;
    /**
     * Creates new form CreateAirlinerJPanel
     */
    

    CreateAirlinerJPanel(JPanel jPanelBody, TravelAgency travelAgencyObj) {
       initComponents();
        setBounds(10, 10, 400, 300);
        setSize(3500, 3360);
         this.jPanelBody=jPanelBody;
         this.travelAgencyObj=travelAgencyObj;
         
             jTextFieldRatingsCreate.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
             
                 jTextFieldAirlinerTotalSeats.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
                 
                     jTextFieldAirlinerWindowSeats.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
                     
                         jTextFieldAirlinerMiddleSeats.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
                         
                             jTextFieldAirlinerAisleSeats.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
                             
                                jTextFieldAirlinerWindowPrice.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (e.getKeyChar() == '.') ||(c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
                                   jTextFieldAirlinerMiddlePrice.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (e.getKeyChar() == '.') ||(c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
                                      jTextFieldAirlinerAislePrice.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (e.getKeyChar() == '.') ||(c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
                                      
                    jTextFieldAirlinerCompanyName.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
               char c=e.getKeyChar();
                if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE )){
                    e.consume();
                }
            }
        });                              
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAirlinerStartTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAirlinerTotalSeats = new javax.swing.JTextField();
        jTextFieldAirlinerWindowPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAirlinerMiddlePrice = new javax.swing.JTextField();
        jTextFieldAirlinerAislePrice = new javax.swing.JTextField();
        jTextFieldAirlinerMiddleSeats = new javax.swing.JTextField();
        jButtonBackCreate = new javax.swing.JButton();
        jTextFieldAirlinerAisleSeats = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldAirlinerWindowSeats = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAirlinerCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCreateAirlinerRecord = new javax.swing.JButton();
        jTextFieldAirlinerFlightName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAirlinerSource = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAirlinerDestination = new javax.swing.JTextField();
        jTextFieldAirlinerEndTime = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldRatingsCreate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setText("End Time");

        jLabel6.setText("Start Time");

        jLabel7.setText("Total Seats Available");

        jLabel9.setText("Price");

        jLabel10.setText("Total Seats");

        jButtonBackCreate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBackCreate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackCreate.setText("<<< Back");
        jButtonBackCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackCreateActionPerformed(evt);
            }
        });

        jLabel15.setText("WINDOW");

        jLabel16.setText("MIDDLE");

        jLabel17.setText("AISLE");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setText("Airliner");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel19.setText("Create Record for Flights");

        jLabel1.setText("Airliner Company Name");

        jLabel2.setText("Flight Number");

        jButtonCreateAirlinerRecord.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCreateAirlinerRecord.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateAirlinerRecord.setText("Create Airliner Record");
        jButtonCreateAirlinerRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAirlinerRecordActionPerformed(evt);
            }
        });

        jTextFieldAirlinerFlightName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAirlinerFlightNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Source");

        jLabel4.setText("Destination");

        jLabel12.setText("(dd-MM-yyyy:HH:mm:SS)");

        jLabel13.setText("Ratings : : : ");

        jLabel8.setText("Number Only *");

        jLabel14.setText("(dd-MM-yyyy:HH:mm:SS)");

        jLabel11.setText("Number Only *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAirlinerTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButtonBackCreate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButtonCreateAirlinerRecord))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldAirlinerWindowSeats)
                                            .addComponent(jTextFieldAirlinerMiddleSeats)
                                            .addComponent(jTextFieldAirlinerAisleSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel10)))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldAirlinerWindowPrice)
                                                .addComponent(jTextFieldAirlinerMiddlePrice)
                                                .addComponent(jTextFieldAirlinerAislePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel9)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldAirlinerDestination, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldAirlinerEndTime))))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAirlinerCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jTextFieldAirlinerFlightName))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRatingsCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAirlinerSource, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAirlinerStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(380, 380, 380))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAirlinerCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldRatingsCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAirlinerFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAirlinerSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAirlinerDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldAirlinerStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAirlinerEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldAirlinerWindowSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAirlinerMiddleSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAirlinerAisleSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldAirlinerTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldAirlinerWindowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAirlinerMiddlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAirlinerAislePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCreateAirlinerRecord)
                .addGap(7, 7, 7)
                .addComponent(jButtonBackCreate)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackCreateActionPerformed
        // TODO add your handling code here:

        jPanelBody.remove(this);
        CardLayout layout=(CardLayout) jPanelBody.getLayout();
        layout.previous(jPanelBody);
    }//GEN-LAST:event_jButtonBackCreateActionPerformed

    private void jButtonCreateAirlinerRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAirlinerRecordActionPerformed
        // TODO add your handling code here:

            String format = "dd-MM-yyyy:HH:mm:SS";
            SimpleDateFormat sdf = new SimpleDateFormat(format);

            String startDate= jTextFieldAirlinerStartTime.getText();
            String endDate= jTextFieldAirlinerEndTime.getText();

            Date flight_startDate = null;
            Date flight_endDate = null;

           
        
        if(jTextFieldAirlinerCompanyName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Airline Company Name.");
        }
        else if(jTextFieldAirlinerFlightName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Airliner's Flight Name.");
        }
        else if(jTextFieldAirlinerSource.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Start Place.");
        }
        else if(jTextFieldAirlinerDestination.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter End Place.");
        }
        else if(jTextFieldAirlinerStartTime.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Start Time.");
        }
        else if(jTextFieldAirlinerEndTime.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter End Time.");
        }else if(jTextFieldAirlinerTotalSeats.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Total Seats in the Flight.");
        }
        else if(jTextFieldAirlinerWindowSeats.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Window Seats.");
        }else if(jTextFieldAirlinerAisleSeats.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Aisle Seats.");
        }
        else if(jTextFieldAirlinerMiddleSeats.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Middle Seats.");
        }else if(jTextFieldAirlinerAislePrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Aisle Seats Price.");
        }
        else if(jTextFieldAirlinerWindowPrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Window Seats  Price.");
        }
        else if(jTextFieldAirlinerMiddlePrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Middle Seats Price.");
        }
        else if (flight_startDate==null) {
        JOptionPane.showMessageDialog(null, "Please enter valid Start date");
         }
         else if (flight_endDate==null) {
        JOptionPane.showMessageDialog(null, "Please enter valid End date");
         }
        else{

            String airlineCompanyName=jTextFieldAirlinerCompanyName.getText();
            String airlineFlightName=jTextFieldAirlinerFlightName.getText();
            String sourcePlace=jTextFieldAirlinerSource.getText();
            String destinationPlace=jTextFieldAirlinerDestination.getText();

           

            int totalSeatsPresent=Integer.parseInt(jTextFieldAirlinerTotalSeats.getText());
            int windowSeats=Integer.parseInt(jTextFieldAirlinerWindowSeats.getText());
            int middleSeats=Integer.parseInt(jTextFieldAirlinerMiddleSeats.getText());
            int aisleSeats=Integer.parseInt(jTextFieldAirlinerAisleSeats.getText());

            double windowPrice=Double.parseDouble(jTextFieldAirlinerWindowPrice.getText());
            double aislePrice= Double.parseDouble(jTextFieldAirlinerAislePrice.getText());
            double middlePrice=Double.parseDouble(jTextFieldAirlinerMiddlePrice.getText());

            int ratingOfAirplane=Integer.parseInt(jTextFieldRatingsCreate.getText());
            
             try {
                flight_startDate = sdf.parse(startDate);
                flight_endDate = sdf.parse(endDate);
            } catch (ParseException ex) {
                Logger.getLogger(CreateAirlinerJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            int totalAllSeats=windowSeats+middleSeats+aisleSeats;
            if(totalSeatsPresent!=totalAllSeats)
            {
               JOptionPane.showMessageDialog(null,"Sum of Window/Middle/Aisle seats should be equal to total Seats"); 
            }
            else
            {
            
            Airplane airplaneObj=travelAgencyObj.addAirliner();
            airplaneObj.setAirlineCompany(airlineCompanyName);
            airplaneObj.setAirlinerName(airlineFlightName);
            airplaneObj.setSourcePlace(sourcePlace);
            airplaneObj.setDestinationPlace(destinationPlace);
            airplaneObj.setStartDate(flight_startDate);
            airplaneObj.setEndDate(flight_endDate);
            airplaneObj.setTotalSeatsAvailable(totalSeatsPresent);
            airplaneObj.setWindowTotal(windowSeats);
            airplaneObj.setAisleTotal(aisleSeats);
            airplaneObj.setMiddleTotal(middleSeats);
            airplaneObj.setWindowPrice(windowPrice);
            airplaneObj.setAislePrice(aislePrice);
            airplaneObj.setMiddlePrice(middlePrice);
            airplaneObj.setMiddlePrice(ratingOfAirplane);
            airplaneObj.setRatings(ratingOfAirplane);

            JOptionPane.showMessageDialog(null, "Airliners Record and corresponding details added Successfully.");
            
            jTextFieldAirlinerCompanyName.setText("");
        jTextFieldAirlinerFlightName.setText("");
        jTextFieldAirlinerSource.setText("");
        jTextFieldAirlinerDestination.setText("");
        jTextFieldAirlinerTotalSeats.setText("");
        jTextFieldAirlinerWindowSeats.setText("");
        jTextFieldAirlinerMiddleSeats.setText("");
        jTextFieldAirlinerAisleSeats.setText("");
        jTextFieldAirlinerWindowPrice.setText("");
        jTextFieldAirlinerAislePrice.setText("");
        jTextFieldAirlinerMiddlePrice.setText("");
        jTextFieldRatingsCreate.setText("");
        jTextFieldAirlinerStartTime.setText("");
        jTextFieldAirlinerEndTime.setText("");
      
        }
        }    
    }//GEN-LAST:event_jButtonCreateAirlinerRecordActionPerformed

    private void jTextFieldAirlinerFlightNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAirlinerFlightNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAirlinerFlightNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCreate;
    private javax.swing.JButton jButtonCreateAirlinerRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAirlinerAislePrice;
    private javax.swing.JTextField jTextFieldAirlinerAisleSeats;
    private javax.swing.JTextField jTextFieldAirlinerCompanyName;
    private javax.swing.JTextField jTextFieldAirlinerDestination;
    private javax.swing.JTextField jTextFieldAirlinerEndTime;
    private javax.swing.JTextField jTextFieldAirlinerFlightName;
    private javax.swing.JTextField jTextFieldAirlinerMiddlePrice;
    private javax.swing.JTextField jTextFieldAirlinerMiddleSeats;
    private javax.swing.JTextField jTextFieldAirlinerSource;
    private javax.swing.JTextField jTextFieldAirlinerStartTime;
    private javax.swing.JTextField jTextFieldAirlinerTotalSeats;
    private javax.swing.JTextField jTextFieldAirlinerWindowPrice;
    private javax.swing.JTextField jTextFieldAirlinerWindowSeats;
    private javax.swing.JTextField jTextFieldRatingsCreate;
    // End of variables declaration//GEN-END:variables
}
