/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Airliner;

import Business.Airplane;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author jhsnehashree
 */
public class ManageAirlinerJPanel extends javax.swing.JPanel {
 private JPanel jPanelBody ;
 private TravelAgency travelAgencyObj;
    /**
     * Creates new form ManageAirlinerJPanel
     */
    

    ManageAirlinerJPanel(JPanel jPanelBody, TravelAgency travelAgencyObj) {
         initComponents();
         setBounds(10, 10, 400, 300);
        setSize(3500, 3360);
         this.jPanelBody=jPanelBody;
         this.travelAgencyObj=travelAgencyObj;
         populateTable();
    }
public void populateTable()
{
       jTableSearchManage.setBackground(Color.pink);
    DefaultTableModel dtm =(DefaultTableModel) jTableSearchManage.getModel();
    dtm.setRowCount(0);
    
    for(Airplane airplaneslst:travelAgencyObj.getAirplaneCompany())
    {
        Object[] row=new Object[15];
        row[0]=airplaneslst;
        row[1]=airplaneslst.getAirlinerName();
        row[2]=airplaneslst.getSourcePlace();
        row[3]=airplaneslst.getDestinationPlace();
        row[4]=airplaneslst.getStartDate();
        row[5]=airplaneslst.getEndDate();
        row[6]=airplaneslst.getTotalSeatsAvailable();
        row[7]=airplaneslst.getTotalSeatsBooked();
        row[8]=airplaneslst.getWindowTotal();
        row[9]=airplaneslst.getAisleTotal();
        row[10]=airplaneslst.getMiddleTotal();
        row[11]=airplaneslst.getWindowPrice();
        row[12]=airplaneslst.getAislePrice();
        row[13]=airplaneslst.getMiddlePrice();
        row[14]=airplaneslst.getRatings();
      
       
        dtm.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSearchManage = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearchCompany = new javax.swing.JTextField();
        jButtonSearchAirliner = new javax.swing.JButton();
        jButtonBackManageTravelAgency = new javax.swing.JButton();
        jTextFieldFromSearch = new javax.swing.JTextField();
        jTextFieldToSearch = new javax.swing.JTextField();
        jButtonDeleteAirliner = new javax.swing.JButton();
        jButtonViewCustomerDetails = new javax.swing.JButton();
        jLabelViewCustomerNames = new javax.swing.JLabel();
        jLabelViewCustomerSeats = new javax.swing.JLabel();
        jLabelViewCustomerPhNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jTableSearchManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Company", "Flight Number", "Source", "Destination", "From Time", "To Time", "Total Available Seats", "Total Seats Booked", "Window Seats", "Aisle Seats", "Middle Seats", "Price Window", "Price Aisle", "Price Middle", "Ratings"
            }
        ));
        jScrollPane1.setViewportView(jTableSearchManage);

        jLabel3.setText("to");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Search Flights");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Airliners");

        jButtonSearchAirliner.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSearchAirliner.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchAirliner.setText("Go/View >>>>");
        jButtonSearchAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchAirlinerActionPerformed(evt);
            }
        });

        jButtonBackManageTravelAgency.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBackManageTravelAgency.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackManageTravelAgency.setText("<< Back");
        jButtonBackManageTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackManageTravelAgencyActionPerformed(evt);
            }
        });

        jTextFieldToSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToSearchActionPerformed(evt);
            }
        });

        jButtonDeleteAirliner.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDeleteAirliner.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteAirliner.setText("Delete Record of Airliner");
        jButtonDeleteAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAirlinerActionPerformed(evt);
            }
        });

        jButtonViewCustomerDetails.setBackground(new java.awt.Color(0, 0, 0));
        jButtonViewCustomerDetails.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewCustomerDetails.setText("View Customer Name and Seat Number Booked");
        jButtonViewCustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewCustomerDetailsActionPerformed(evt);
            }
        });

        jLabelViewCustomerNames.setText("-");

        jLabelViewCustomerSeats.setText("-");

        jLabelViewCustomerPhNo.setText("-");

        jLabel4.setText("Customer Name");

        jLabel5.setText("Seat Number Booked");

        jLabel6.setText("Customer Phone No.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))
                            .addComponent(jButtonBackManageTravelAgency)
                            .addComponent(jButtonSearchAirliner)
                            .addComponent(jTextFieldSearchCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldFromSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDeleteAirliner)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonViewCustomerDetails)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelViewCustomerPhNo)
                                    .addComponent(jLabelViewCustomerSeats)
                                    .addComponent(jLabelViewCustomerNames))))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jTextFieldSearchCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFromSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearchAirliner))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeleteAirliner)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonViewCustomerDetails)
                            .addComponent(jLabelViewCustomerNames)
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelViewCustomerSeats)
                            .addComponent(jLabel5)))
                    .addComponent(jButtonBackManageTravelAgency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelViewCustomerPhNo)
                    .addComponent(jLabel6))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAirlinerActionPerformed
        // TODO add your handling code here:
        if(jTextFieldSearchCompany.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Airline Company to be Searched.");
        }
        else{
            Airplane airplaneCompanySearch=travelAgencyObj.searchAirplaneCompany(jTextFieldSearchCompany.getText());
          Airplane toFromSearch=travelAgencyObj.searchFromTo(jTextFieldToSearch.getText(),jTextFieldFromSearch.getText());
            if(airplaneCompanySearch==null)
            {
                JOptionPane.showMessageDialog(null, "Airline Company not found.");
            }
            else if (toFromSearch==null){
                ViewAirlinerJPanel panel=new ViewAirlinerJPanel(jPanelBody,airplaneCompanySearch);
                jPanelBody.add("ViewAirlinerJPanel",panel);
                CardLayout layout=(CardLayout) jPanelBody.getLayout();
                layout.next(jPanelBody);
            }
            else{
                  if(jTextFieldToSearch.getText().equals("") && jTextFieldFromSearch.getText().equals(""))
                {
                  JOptionPane.showMessageDialog(null, "Please enter From and To Locations both.");   
                }
                else{
                ViewAirlinerJPanel panel=new ViewAirlinerJPanel(jPanelBody,toFromSearch);
                jPanelBody.add("ViewAirlinerJPanel",panel);
                CardLayout layout=(CardLayout) jPanelBody.getLayout();
                layout.next(jPanelBody);
                  }
            }
        }
    }//GEN-LAST:event_jButtonSearchAirlinerActionPerformed

    private void jButtonBackManageTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackManageTravelAgencyActionPerformed
        // TODO add your handling code here:
        jPanelBody.remove(this);
        CardLayout layout=(CardLayout) jPanelBody.getLayout();
        layout.previous(jPanelBody);
    }//GEN-LAST:event_jButtonBackManageTravelAgencyActionPerformed

    private void jButtonDeleteAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAirlinerActionPerformed
        // TODO add your handling code here:
         
        int selectedRow=jTableSearchManage.getSelectedRow();
        if(selectedRow>=0)
        {
         int dialogButton=JOptionPane.YES_NO_OPTION;
         int dialogResult=JOptionPane.showConfirmDialog(null, "Are you sure to Delete the Airliner ??","Warning",dialogButton);
         if(dialogResult==JOptionPane.YES_OPTION)
         {
            Airplane airplane_delete=(Airplane) jTableSearchManage.getValueAt(selectedRow, 0);
            travelAgencyObj.deleteAirplane(airplane_delete);
            populateTable();
         }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table shown.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteAirlinerActionPerformed

    private void jButtonViewCustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewCustomerDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow=jTableSearchManage.getSelectedRow();
        if(selectedRow<0)
        {
              JOptionPane.showMessageDialog(null, "Please select a row from the table shown.","Warning",JOptionPane.WARNING_MESSAGE);
        }
         else{
       
           Airplane airways_Customer=(Airplane) jTableSearchManage.getValueAt(selectedRow, 0);

         jLabelViewCustomerNames.setText(airways_Customer.getCustomerName());
         jLabelViewCustomerPhNo.setText(airways_Customer.getCustomerPhoneNo());
         jLabelViewCustomerSeats.setText(airways_Customer.getCustomerSeatNo());

        }
    }//GEN-LAST:event_jButtonViewCustomerDetailsActionPerformed

    private void jTextFieldToSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldToSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackManageTravelAgency;
    private javax.swing.JButton jButtonDeleteAirliner;
    private javax.swing.JButton jButtonSearchAirliner;
    private javax.swing.JButton jButtonViewCustomerDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelViewCustomerNames;
    private javax.swing.JLabel jLabelViewCustomerPhNo;
    private javax.swing.JLabel jLabelViewCustomerSeats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSearchManage;
    private javax.swing.JTextField jTextFieldFromSearch;
    private javax.swing.JTextField jTextFieldSearchCompany;
    private javax.swing.JTextField jTextFieldToSearch;
    // End of variables declaration//GEN-END:variables
}
